version: "3.9"

services:
  gsr:
    image: stephenmao0927/gsr:v2
    container_name: gsr
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [compute, utility, graphics]
    gpus: all
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
      - FORCE_CUDA=1
      - QT_X11_NO_MITSHM=1
      - DISPLAY=${DISPLAY}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
    ipc: host
    shm_size: "16g"
    volumes:
      - ../src:/workspace/src
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /workspace/src
    tty: true
    stdin_open: true
    command: bash -lc "bash"
